/**
 * export-3d.ts
 *
 * Exports voxel models to:
 *  - OBJ + MTL  — coloured OBJ with a companion material file, zipped together.
 *    Bambu Studio, PrusaSlicer, Cura and every other slicer reads this natively
 *    and respects per-object / per-face colours with no warnings.
 *
 *  - 3MF  — XML-based format with a <m:colorgroup>, packed into a spec-compliant
 *    ZIP.  Includes the `slic3rpe:3mf_version` metadata tag that PrusaSlicer /
 *    BambuStudio look for, which reduces the "generated by another app" dialog to
 *    a simple geometry-only import (colour is still preserved correctly).
 *    Note: Bambu Studio's warning cannot be completely suppressed — it is
 *    hardcoded to protect users from missing slicer settings when opening files
 *    that were not saved by BambuStudio itself.  The geometry and colour will
 *    always be correct; just click "Load geometry only".
 *
 *  - Binary STL  (no colour) — plain geometry, compatible with all slicers.
 *    Colour is not supported in STL by any major modern slicer; use OBJ or 3MF
 *    for coloured prints.
 *
 * No external runtime dependencies — the ZIP archives are built with a small
 * hand-rolled deflate-free (STORE method) ZIP writer.
 */

import type { Voxel } from './voxel-store';

/* ───────────────────────────────────────────────────────────────────────────
   Shared geometry helpers
─────────────────────────────────────────────────────────────────────────── */

const FACE_NORMALS: [number, number, number][] = [
  [0, 0, 1],   // front  (+Z)
  [0, 0, -1],  // back   (-Z)
  [0, 1, 0],   // top    (+Y)
  [0, -1, 0],  // bottom (-Y)
  [1, 0, 0],   // right  (+X)
  [-1, 0, 0],  // left   (-X)
];

const FACE_QUADS: [number, number, number][][] = [
  [[-0.5, -0.5, 0.5],  [0.5, -0.5, 0.5],  [0.5, 0.5, 0.5],  [-0.5, 0.5, 0.5]],   // front
  [[0.5, -0.5, -0.5],  [-0.5, -0.5, -0.5], [-0.5, 0.5, -0.5], [0.5, 0.5, -0.5]],  // back
  [[-0.5, 0.5, -0.5],  [0.5, 0.5, -0.5],  [0.5, 0.5, 0.5],  [-0.5, 0.5, 0.5]],   // top
  [[-0.5, -0.5, 0.5],  [0.5, -0.5, 0.5],  [0.5, -0.5, -0.5], [-0.5, -0.5, -0.5]], // bottom
  [[0.5, -0.5, 0.5],   [0.5, -0.5, -0.5], [0.5, 0.5, -0.5],  [0.5, 0.5, 0.5]],   // right
  [[-0.5, -0.5, -0.5], [-0.5, -0.5, 0.5], [-0.5, 0.5, 0.5],  [-0.5, 0.5, -0.5]], // left
];

interface Triangle {
  normal: [number, number, number];
  v0: [number, number, number];
  v1: [number, number, number];
  v2: [number, number, number];
  color: string; // hex e.g. "#FF0000"
}

/** Build triangles, culling shared internal faces between adjacent voxels. */
function buildTriangles(voxels: Voxel[]): Triangle[] {
  const occupied = new Set<string>(voxels.map((v) => `${v.x},${v.y},${v.z}`));
  const FACE_DIRS: [number, number, number][] = [
    [0, 0, 1], [0, 0, -1], [0, 1, 0], [0, -1, 0], [1, 0, 0], [-1, 0, 0],
  ];

  const FACE_NAMES = ['front', 'back', 'top', 'bottom', 'right', 'left'] as const;

  const triangles: Triangle[] = [];

  for (const voxel of voxels) {
    for (let f = 0; f < 6; f++) {
      const [dx, dy, dz] = FACE_DIRS[f];
      if (occupied.has(`${voxel.x + dx},${voxel.y + dy},${voxel.z + dz}`)) continue;

      const quad = FACE_QUADS[f];
      const normal = FACE_NORMALS[f];
      const ox = voxel.x, oy = voxel.y, oz = voxel.z;
      const faceColor = voxel.faces?.[FACE_NAMES[f]] || voxel.color;

      const addTri = (
        a: [number, number, number],
        b: [number, number, number],
        c: [number, number, number]
      ) =>
        triangles.push({
          normal,
          v0: [ox + a[0], oy + a[1], oz + a[2]],
          v1: [ox + b[0], oy + b[1], oz + b[2]],
          v2: [ox + c[0], oy + c[1], oz + c[2]],
          color: faceColor,
        });

      addTri(quad[0], quad[1], quad[2]);
      addTri(quad[0], quad[2], quad[3]);
    }
  }
  return triangles;
}

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

function fmt(n: number, dp = 6): string {
  return n.toFixed(dp);
}

/* ───────────────────────────────────────────────────────────────────────────
   OBJ + MTL export  (best colour support across all slicers)
─────────────────────────────────────────────────────────────────────────── */

/**
 * Build OBJ and MTL file contents.
 * Each unique voxel colour becomes one material; faces are grouped by material
 * so slicers can assign them to separate extruders / filaments.
 */
function buildOBJ(voxels: Voxel[]): { obj: string; mtl: string } {
  const tris = buildTriangles(voxels);

  // Collect unique colours
  const colors = [...new Set(tris.map((t) => t.color))];
  const colorIdx = new Map<string, number>(colors.map((c, i) => [c, i]));

  // Deduplicate vertices
  const vertMap = new Map<string, number>();
  const vertList: [number, number, number][] = [];

  const addVert = (v: [number, number, number]): number => {
    const key = `${v[0]},${v[1]},${v[2]}`;
    let idx = vertMap.get(key);
    if (idx === undefined) {
      idx = vertList.length + 1; // OBJ is 1-indexed
      vertList.push(v);
      vertMap.set(key, idx);
    }
    return idx;
  };

  // Group triangles by colour
  const groups = new Map<string, { i0: number; i1: number; i2: number }[]>();
  for (const color of colors) groups.set(color, []);

  for (const tri of tris) {
    groups.get(tri.color)!.push({
      i0: addVert(tri.v0),
      i1: addVert(tri.v1),
      i2: addVert(tri.v2),
    });
  }

  // ── OBJ ──────────────────────────────────────────────────────────────────
  const objLines: string[] = [
    '# Voxel Editor — OBJ export',
    'mtllib voxel-model.mtl',
    '',
  ];

  for (const [x, y, z] of vertList) {
    objLines.push(`v ${fmt(x)} ${fmt(y)} ${fmt(z)}`);
  }
  objLines.push('');

  for (const color of colors) {
    const matName = `mat_${colorIdx.get(color)}`;
    objLines.push(`usemtl ${matName}`, `g group_${matName}`);
    for (const { i0, i1, i2 } of groups.get(color)!) {
      objLines.push(`f ${i0} ${i1} ${i2}`);
    }
    objLines.push('');
  }

  // ── MTL ──────────────────────────────────────────────────────────────────
  const mtlLines: string[] = ['# Voxel Editor — MTL export', ''];

  for (const color of colors) {
    const [r, g, b] = hexToRgb(color);
    const rf = (r / 255).toFixed(4);
    const gf = (g / 255).toFixed(4);
    const bf = (b / 255).toFixed(4);
    const matName = `mat_${colorIdx.get(color)}`;
    mtlLines.push(
      `newmtl ${matName}`,
      `Ka ${rf} ${gf} ${bf}`,
      `Kd ${rf} ${gf} ${bf}`,
      `Ks 0.1000 0.1000 0.1000`,
      `Ns 10`,
      `d 1`,
      `illum 2`,
      ''
    );
  }

  return { obj: objLines.join('\n'), mtl: mtlLines.join('\n') };
}

/** Export voxels as a ZIP containing voxel-model.obj + voxel-model.mtl */
export function exportOBJ(voxels: Voxel[]): Blob {
  const { obj, mtl } = buildOBJ(voxels);
  const enc = new TextEncoder();
  const zip = buildZip([
    { name: 'voxel-model.obj', data: enc.encode(obj) },
    { name: 'voxel-model.mtl', data: enc.encode(mtl) },
  ]);
  return new Blob([zip], { type: 'application/zip' });
}

/* ───────────────────────────────────────────────────────────────────────────
   Binary STL export  (geometry only — no colour)
─────────────────────────────────────────────────────────────────────────── */

export function exportSTL(voxels: Voxel[]): Blob {
  const tris = buildTriangles(voxels);
  const numTris = tris.length;
  const buffer = new ArrayBuffer(84 + numTris * 50);
  const view = new DataView(buffer);

  const header = 'Voxel Editor STL — use OBJ or 3MF for colour';
  for (let i = 0; i < Math.min(header.length, 80); i++) {
    view.setUint8(i, header.charCodeAt(i));
  }
  view.setUint32(80, numTris, true);

  let offset = 84;
  for (const tri of tris) {
    view.setFloat32(offset, tri.normal[0], true); offset += 4;
    view.setFloat32(offset, tri.normal[1], true); offset += 4;
    view.setFloat32(offset, tri.normal[2], true); offset += 4;
    view.setFloat32(offset, tri.v0[0], true); offset += 4;
    view.setFloat32(offset, tri.v0[1], true); offset += 4;
    view.setFloat32(offset, tri.v0[2], true); offset += 4;
    view.setFloat32(offset, tri.v1[0], true); offset += 4;
    view.setFloat32(offset, tri.v1[1], true); offset += 4;
    view.setFloat32(offset, tri.v1[2], true); offset += 4;
    view.setFloat32(offset, tri.v2[0], true); offset += 4;
    view.setFloat32(offset, tri.v2[1], true); offset += 4;
    view.setFloat32(offset, tri.v2[2], true); offset += 4;
    view.setUint16(offset, 0, true); offset += 2; // attribute byte (no colour)
  }

  return new Blob([buffer], { type: 'application/octet-stream' });
}

/* ───────────────────────────────────────────────────────────────────────────
   3MF export  (colour via <m:colorgroup>)
─────────────────────────────────────────────────────────────────────────── */

function build3MFModel(voxels: Voxel[]): string {
  const tris = buildTriangles(voxels);

  const colorMap = new Map<string, number>();
  for (const tri of tris) {
    if (!colorMap.has(tri.color)) colorMap.set(tri.color, colorMap.size);
  }

  const vertMap = new Map<string, number>();
  const vertices: [number, number, number][] = [];

  const addVert = (v: [number, number, number]): number => {
    const key = `${v[0]},${v[1]},${v[2]}`;
    let idx = vertMap.get(key);
    if (idx === undefined) {
      idx = vertices.length;
      vertices.push(v);
      vertMap.set(key, idx);
    }
    return idx;
  };

  const triList: { v0: number; v1: number; v2: number; colorIdx: number }[] = [];
  for (const tri of tris) {
    triList.push({
      v0: addVert(tri.v0),
      v1: addVert(tri.v1),
      v2: addVert(tri.v2),
      colorIdx: colorMap.get(tri.color) ?? 0,
    });
  }

  const colorGroupId = 1;
  const objectId = 2;

  const colorEntries = [...colorMap.entries()]
    .sort((a, b) => a[1] - b[1])
    .map(([hex]) => {
      const [r, g, b] = hexToRgb(hex);
      return `      <m:color color="#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}ff" />`;
    })
    .join('\n');

  const vertexEntries = vertices
    .map(([x, y, z]) => `        <vertex x="${fmt(x, 4)}" y="${fmt(y, 4)}" z="${fmt(z, 4)}" />`)
    .join('\n');

  const triangleEntries = triList
    .map(
      ({ v0, v1, v2, colorIdx }) =>
        `        <triangle v1="${v0}" v2="${v1}" v3="${v2}" pid="${colorGroupId}" p1="${colorIdx}" />`
    )
    .join('\n');

  // slic3rpe:3mf_version is the key metadata tag that tells PrusaSlicer-based
  // slicers (including BambuStudio) the file version.  Without it the software
  // shows a more alarming warning.  With it, the prompt is reduced to a simple
  // "load geometry only" confirmation — geometry and colour remain correct.
  const now = new Date().toISOString().split('T')[0];
  return `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US"
  xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"
  xmlns:m="http://schemas.microsoft.com/3dmanufacturing/material/2015/02"
  xmlns:slic3rpe="http://schemas.slic3r.org/3mf/2017/06">
  <metadata name="Application">Voxel Editor</metadata>
  <metadata name="Title">Voxel Model</metadata>
  <metadata name="CreationDate">${now}</metadata>
  <metadata name="slic3rpe:3mf_version">2</metadata>
  <resources>
    <m:colorgroup id="${colorGroupId}">
${colorEntries}
    </m:colorgroup>
    <object id="${objectId}" type="model">
      <mesh>
        <vertices>
${vertexEntries}
        </vertices>
        <triangles>
${triangleEntries}
        </triangles>
      </mesh>
    </object>
  </resources>
  <build>
    <item objectid="${objectId}" />
  </build>
</model>`;
}

export function export3MF(voxels: Voxel[]): Blob {
  const enc = new TextEncoder();

  const contentTypes = enc.encode(
    `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" />
  <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml" />
</Types>`
  );

  const rels = enc.encode(
    `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel" />
</Relationships>`
  );

  const model = enc.encode(build3MFModel(voxels));

  const zip = buildZip([
    { name: '[Content_Types].xml', data: contentTypes },
    { name: '_rels/.rels', data: rels },
    { name: '3D/3dmodel.model', data: model },
  ]);

  return new Blob([zip], { type: 'application/vnd.ms-package.3dmanufacturing-3dmodel+xml' });
}

/* ───────────────────────────────────────────────────────────────────────────
   Minimal ZIP builder (STORE / no compression)
─────────────────────────────────────────────────────────────────────────── */

interface ZipEntry { name: string; data: Uint8Array; }

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let j = 0; j < 8; j++) c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1);
    t[i] = c;
  }
  return t;
})();

function crc32(data: Uint8Array): number {
  let crc = 0xffffffff;
  for (let i = 0; i < data.length; i++) crc = (crc >>> 8) ^ CRC_TABLE[(crc ^ data[i]) & 0xff];
  return (crc ^ 0xffffffff) >>> 0;
}

function u16(n: number): Uint8Array { const b = new Uint8Array(2); new DataView(b.buffer).setUint16(0, n, true); return b; }
function u32(n: number): Uint8Array { const b = new Uint8Array(4); new DataView(b.buffer).setUint32(0, n, true); return b; }
function utf8(s: string): Uint8Array { return new TextEncoder().encode(s); }

function concat(...parts: Uint8Array[]): Uint8Array {
  const out = new Uint8Array(parts.reduce((s, p) => s + p.length, 0));
  let off = 0;
  for (const p of parts) { out.set(p, off); off += p.length; }
  return out;
}

function buildZip(entries: ZipEntry[]): Uint8Array {
  const locals: Uint8Array[] = [];
  const centrals: Uint8Array[] = [];
  const offsets: number[] = [];
  let pos = 0;

  for (const e of entries) {
    const name = utf8(e.name);
    const crc = crc32(e.data);
    const sz = e.data.length;
    offsets.push(pos);

    const local = concat(
      new Uint8Array([0x50, 0x4b, 0x03, 0x04]),
      u16(20), u16(0), u16(0), u16(0), u16(0),
      u32(crc), u32(sz), u32(sz),
      u16(name.length), u16(0),
      name, e.data
    );
    locals.push(local);
    pos += local.length;
  }

  for (let i = 0; i < entries.length; i++) {
    const name = utf8(entries[i].name);
    const crc = crc32(entries[i].data);
    const sz = entries[i].data.length;
    centrals.push(
      concat(
        new Uint8Array([0x50, 0x4b, 0x01, 0x02]),
        u16(20), u16(20), u16(0), u16(0), u16(0), u16(0),
        u32(crc), u32(sz), u32(sz),
        u16(name.length), u16(0), u16(0), u16(0), u16(0),
        u32(0), u32(offsets[i]),
        name
      )
    );
  }

  const cd = concat(...centrals);
  return concat(
    ...locals, cd,
    concat(
      new Uint8Array([0x50, 0x4b, 0x05, 0x06]),
      u16(0), u16(0),
      u16(entries.length), u16(entries.length),
      u32(cd.length), u32(pos),
      u16(0)
    )
  );
}

/* ───────────────────────────────────────────────────────────────────────────
   Utility
─────────────────────────────────────────────────────────────────────────── */

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
